# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 07:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esloq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^([0-9a-f]{2}:){5}([0-9a-f]{2})$', 'Invalid MAC address')])),
                ('key', models.BinaryField(max_length=32)),
                ('name', models.CharField(max_length=20)),
                ('nonce', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EsloqUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firebase_id', models.CharField(blank=True, max_length=28, null=True, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FcmRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_id', models.CharField(max_length=512)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esloq.EsloqUser')),
            ],
        ),
        migrations.CreateModel(
            name='LockAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField()),
                ('lock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esloq.Esloq')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esloq.EsloqUser')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_time', models.PositiveIntegerField(default=time.time)),
                ('lock_state', models.BooleanField()),
                ('lock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esloq.Esloq')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esloq.EsloqUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lockaccess',
            unique_together=set([('lock_id', 'user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='fcmregistration',
            unique_together=set([('user_id', 'registration_id')]),
        ),
    ]
