# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esloq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcmregistration',
            old_name='registration_id',
            new_name='registration_token',
        ),
        migrations.AlterUniqueTogether(
            name='fcmregistration',
            unique_together=set([('user_id', 'registration_token')]),
        ),
    ]
