/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_esloq_esloqapp_Cryptography */

#ifndef _Included_com_esloq_esloqapp_Cryptography
#define _Included_com_esloq_esloqapp_Cryptography
#ifdef __cplusplus
extern "C" {
#endif
#undef com_esloq_esloqapp_Cryptography_NONCE_LENGTH
#define com_esloq_esloqapp_Cryptography_NONCE_LENGTH 24L
#undef com_esloq_esloqapp_Cryptography_MAC_LENGTH
#define com_esloq_esloqapp_Cryptography_MAC_LENGTH 16L
/*
 * Class:     com_esloq_esloqapp_Cryptography
 * Method:    encrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_esloq_esloqapp_Cryptography_encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_esloq_esloqapp_Cryptography
 * Method:    decrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_esloq_esloqapp_Cryptography_decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
